Zdorro button
KefirNot/mining-calculator pull request #4
Opened 2022-02-21 18:23 UTC by zdorro

2022-02-22 08:22 UTC, KefirNot requested changes

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        var facts = ['Ваза для вина - это декантер',
есть вопрос к форматированию, правильно делать так:
const array = [
  'asda',
  'ololo',
]

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        var fact = facts[Math.floor(Math.random() * facts.length)];
надо сделать отдельный файлик utils.js и вынести в него функцию getRandomInt
в этой строчке надо эту функцию будет использовать

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        var facts = ['Ваза для вина - это декантер',
старайся использовать const и let, почитай статью про их отличия, но сильно не зацикливайся, скорее всего все не поймешь

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        var facts = ['Ваза для вина - это декантер',
надо вынести facts из твоей кнопки выше (например перед тем как ты объявляешь функцию)
еще надо назвать в соответствии с правилом называния констант:
const FACTS = [...];

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        'Муравьи спят 250 раз в день',
хочу быть муравьем

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        var iSmart = ['Посмотрите, какая я умная кнопка!', 'Ебать я умная',
тоже что и для facts

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        var iSmart = ['Посмотрите, какая я умная кнопка!', 'Ебать я умная',
более правильное именование было бы SMART_FACTS

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        var smart = iSmart[Math.floor(Math.random() * iSmart.length)];
можно написать красивее и понятнее
посмотри как работает contains у массивов

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        var smart = iSmart[Math.floor(Math.random() * iSmart.length)];
имя переменной означающая тру или фолс обычно должно начинаться с isSomething

 в твоем случае isSmart

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        <button style={{backgroundColor: "yellow", width: "600px",
попробуй стили вынести в css

писать прям в стили можно, но лучше не делать

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        <button style={{backgroundColor: "yellow", width: "600px",
проблемы с форматированием, у такого кода плохая читабельность, пиши так:
<tag
    prop={1}
    lal="azaza"
/>

2022-02-22 08:22 UTC, KefirNot commented on src/VerySmartButton/VerySmartButton.jsx
> +        <button style={{backgroundColor: "yellow", width: "600px",
кароч потом покажу

2022-02-22 08:24 UTC, KefirNot commented
почему-то у тебя лого добавилось в ПР, надо разобраться с этим

2022-02-22 09:43 UTC, zdorro commented on src/VerySmartButton/VerySmartButton.jsx
> +        <button style={{backgroundColor: "yellow", width: "600px",
Везде в интернетах пишут, что стили так и подключаются, но я опять начинаю разбивать клаву, потому что что-то не работает.
![Screenshot_1](https://user-images.githubusercontent.com/90772559/155105606-7d2d240d-fd27-43cf-8324-7c898f2038ca.png)
![Screenshot_2](https://user-images.githubusercontent.com/90772559/155105766-01a7a30c-a939-4194-8d89-2ddb5262e068.png)
![Screenshot_3](https://user-images.githubusercontent.com/90772559/155105792-db8373e8-1269-4e03-9ef7-5d27bad8cdd8.png)

2022-02-22 12:07 UTC, zdorro commented on src/VerySmartButton/VerySmartButton.jsx
> +        var facts = ['Ваза для вина - это декантер',
Ты имеешь в виду, вынести facts в главный файл (App.js)?
Потому что если я выношу переменные в файле .jsx за функцию и прописываю их перед "export default function VerySmartButton({ children }) ", то функция их не видит, и пишет "undefined".

2022-02-24 08:55 UTC, zdorro commented on src/VerySmartButton/VerySmartButton.jsx
> +        var facts = ['Ваза для вина - это декантер',
Сделано!

2022-02-24 08:56 UTC, zdorro commented on src/VerySmartButton/VerySmartButton.jsx
> +        var fact = facts[Math.floor(Math.random() * facts.length)];
Вынес

2022-02-24 19:07 UTC, KefirNot approved these changes

2022-02-24 19:16 UTC, KefirNot requested changes

2022-02-24 19:16 UTC, KefirNot commented on src/VerySmartButton/utils.js
> +    return massive[Math.floor(Math.random() * massive.length)];
1) название getRandomInt
2) должна возвращать целое число, а не элемент массива. об этом буквально в названии функции сказано

2022-02-24 19:17 UTC, KefirNot commented on src/App.js
> +        <VerySmartButton FACT_MASS={[
это завтра на созвоне обсудим

2022-02-25 08:12 UTC, merged